name:                substrate
version:             0.1.0.0
github:              "ChrisPenner/substrate"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/substrate#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- mtl
- unliftio
- lens

library:
  source-dirs: src

executables:
  substrate:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - substrate

tests:
  substrate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - substrate
    - hspec
    - text
    - raw-strings-qq
